=== GreatCowBASIC/GCB_Gold/Build/ppstool/devices/pcg.xsd
<?xml version="1.0"?>
<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="device">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="manager" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="pins" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="manager" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="AlternatePinFunction" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="modules" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="manager" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="dosid" use="optional"/>
            <xs:attribute ref="id" use="optional"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="rev" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="pinAlias">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="ppsSupport" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="alias" use="required"/>
            <xs:attribute ref="module"/>
            <xs:attribute ref="value"  use="optional"/>
            <xs:attribute ref="direction"  use="optional"/>
            <xs:attribute ref="remapTo"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="ppsSupport">
        <xs:complexType mixed="true">
            <xs:attribute ref="pps" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="constraint">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="constraintVariable" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="type"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="constraintVariable">
        <xs:complexType mixed="true">
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="value"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="interrupt">
        <xs:complexType mixed="true">
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="flag" use="required"/>
            <xs:attribute ref="enable"  use="required"/>
            <xs:attribute ref="vector"  use="optional"/>
            <xs:attribute ref="irq"  use="optional"/>
            <xs:attribute ref="handler_name"  use="optional"/>
            <xs:attribute ref="priority"  use="optional"/>
            <xs:attribute ref="sub_priority"  use="optional"/>
            <xs:attribute ref="priority_range"  use="optional"/>
            <xs:attribute ref="description"  use="optional"/>
            <xs:attribute ref="sub_priority_range"  use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="pinNumber">
        <xs:complexType mixed="true">
            <xs:attribute ref="package" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>

<!--    <xs:element name="pps">
        <xs:complexType mixed="true">
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>-->
    
    <xs:element id="pin" name="pin">
        <xs:complexType mixed="true">
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="pinNumber" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="pinAlias" minOccurs="1" maxOccurs="unbounded"/>
            </xs:choice>
            <!-- FIXME: lat, name, and tris should not be optional. How to handle Vdd? -->
            <xs:attribute ref="ansel"/>
            <xs:attribute ref="lat" use="optional"/>
            <xs:attribute ref="name" use="optional"/>
            <xs:attribute ref="od" />
            <xs:attribute ref="tris" use="optional"/>
            <xs:attribute ref="pps" use="optional"/>
            <xs:attribute ref="ppsValue" use="optional"/>
            <xs:attribute ref="wpu"/>
            <xs:attribute ref="cn"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="pins">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="pin" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        
    <xs:element name="manager">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="additional_properties" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="interrupt"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="property"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="modules" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="additional_properties">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="pinAlias" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="name" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType mixed="true">
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="type"/>
            <xs:attribute ref="value" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="option">
        <xs:complexType mixed="true">
            <xs:attribute ref="description"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="alias" use="optional"/>
            <xs:attribute ref="value" use="optional"/>
            <xs:attribute ref="mode" use="optional"/>
            <xs:attribute ref="isdefault" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="setting">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="option" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="alias"/>
            <!-- FIXME: should default be "required"? -->
            <xs:attribute ref="default" use="optional"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="mask" use="optional"/>
            <xs:attribute ref="type" use="optional"/>
            <xs:attribute ref="porDefault" use="optional"/>
            <xs:attribute type="xs:string" name="description"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="register">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="constraint" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="setting" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="alias" />
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="default" use="optional"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="width" use="optional"/>
            <xs:attribute name="desc" type="xs:normalizedString" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="module">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="interrupt"  minOccurs="0" maxOccurs="unbounded"/>
                <!-- FIXME: Can this be tightened up?
                            Elements added after the 'register' element
                            still must be defined in the Schema, but there
                            is no restriction as to what type of element
                            can be used. -->
                <xs:element ref="property"  minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="property"  minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute ref="dosid" use="optional"/>
            <xs:attribute ref="group" use="optional"/>
            <xs:attribute ref="name" use="required"/>
            <xs:attribute ref="subgroup" use="optional"/>
            <xs:attribute ref="type" use="required"/>
            <xs:attribute ref="version" use="optional"/>
            <xs:attribute ref="sub_version" use="optional"/>
            <xs:attribute ref="instance" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="modules">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="module" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="AlternatePinFunction">
        <xs:complexType mixed="true">
            <xs:sequence>
                <!-- FIXME: should minOccurs be "1"? -->
                <xs:element ref="register" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:attribute name="id" type="xs:normalizedString"/>
    <xs:attribute name="lat" type="xs:normalizedString"/>
    <xs:attribute name="name" type="xs:normalizedString"/>
    <xs:attribute name="group" type="xs:normalizedString"/>
    <xs:attribute name="subgroup" type="xs:normalizedString"/>
    <xs:attribute name="od" type="xs:normalizedString"/>
    <xs:attribute name="tris" type="xs:normalizedString"/>
    <xs:attribute name="alias" type="xs:normalizedString"/>
    <xs:attribute name="module" type="xs:normalizedString"/>
    <xs:attribute name="package" type="xs:normalizedString"/>
    <xs:attribute name="value" type="xs:normalizedString"/>
    <xs:attribute name="default" type="xs:normalizedString"/>
    <xs:attribute name="display_type" type="xs:normalizedString"/>
    <xs:attribute name="type" type="xs:normalizedString"/>
    <xs:attribute name="pps" type="xs:normalizedString"/>
    <xs:attribute name="ppsValue" type="xs:normalizedString"/>
    <xs:attribute name="mask" type="xs:normalizedString"/>
    <xs:attribute name="version" type="xs:normalizedString"/>
    <xs:attribute name="description" type="xs:normalizedString"/>
    <xs:attribute name="direction" type="xs:normalizedString"/>
    <xs:attribute name="ansel" type="xs:normalizedString"/>
    <xs:attribute name="wpu" type="xs:normalizedString"/>
    <xs:attribute name="rev" type="xs:normalizedString"/>
    <xs:attribute name="dosid" type="xs:normalizedString"/>
    <xs:attribute name="sub_version" type="xs:normalizedString"/>
    <xs:attribute name="cn" type="xs:normalizedString"/>
    <xs:attribute name="flag" type="xs:normalizedString"/>
    <xs:attribute name="enable" type="xs:normalizedString"/>
    <xs:attribute name="priority" type="xs:normalizedString"/>
    <xs:attribute name="vector" type="xs:normalizedString"/>
    <xs:attribute name="irq" type="xs:normalizedString"/>
    <xs:attribute name="sub_priority" type="xs:normalizedString"/>
    <xs:attribute name="priority_range" type="xs:normalizedString"/>
    <xs:attribute name="sub_priority_range" type="xs:normalizedString"/>
    <xs:attribute name="handler_name" type="xs:normalizedString"/>
    <xs:attribute name="remapTo" type="xs:normalizedString"/>
    <xs:attribute name="mode" type="xs:normalizedString"/>
    <xs:attribute name="porDefault" type="xs:normalizedString"/>
    <xs:attribute name="isdefault" type="xs:normalizedString"/>
    <xs:attribute name="instance" type="xs:normalizedString"/>
    <xs:attribute name="width" type="xs:normalizedString"/>
</xs:schema>

=== GreatCowBASIC/GCB_Gold/Build/ppstool/devices/pic16f1574_description.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<device xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" dosid="02891" id="" name="PIC16F1574" rev="" xsi:noNamespaceSchemaLocation="PCG.xsd">
    <manager name="System Module">
        <register alias="CONFIG1" name="CONFIG1" width="0x10">
            <setting alias="FOSC" default="ECH" name="FOSC" description="Oscillator Selection Bits">
                <option description="ECH, External Clock, High Power Mode (4-32 MHz); device clock supplied to CLKIN pin" name="ECH" alias="ECH" value="0x3"/>
                <option description="ECM, External Clock, Medium Power Mode (0.5-4 MHz); device clock supplied to CLKIN pin" name="ECM" alias="ECM" value="0x2"/>
                <option description="ECL, External Clock, Low Power Mode (0-0.5 MHz); device clock supplied to CLKIN pin" name="ECL" alias="ECL" value="0x1"/>
                <option description="INTOSC oscillator; I/O function on CLKIN pin" name="INTOSC" alias="INTOSC" value="0x0"/>
            </setting>
            <setting alias="WDTE" default="ON" name="WDTE" description="Watchdog Timer Enable">
                <option description="WDT enabled" name="ON" alias="ON" value="0x18"/>
                <option description="WDT enabled while running and disabled in Sleep" name="NSLEEP" alias="NSLEEP" value="0x10"/>
                <option description="WDT controlled by the SWDTEN bit in the WDTCON register" name="SWDTEN" alias="SWDTEN" value="0x8"/>
                <option description="WDT disabled" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="PWRTE" default="OFF" name="PWRTE" description="Power-up Timer Enable">
                <option description="PWRT disabled" name="OFF" alias="OFF" value="0x20"/>
                <option description="PWRT enabled" name="ON" alias="ON" value="0x0"/>
            </setting>
            <setting alias="MCLRE" default="ON" name="MCLRE" description="MCLR Pin Function Select">
                <option description="MCLR/VPP pin function is MCLR" name="ON" alias="ON" value="0x40"/>
                <option description="MCLR/VPP pin function is digital input" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="CP" default="OFF" name="CP" description="Flash Program Memory Code Protection">
                <option description="Program memory code protection is disabled" name="OFF" alias="OFF" value="0x80"/>
                <option description="Program memory code protection is enabled" name="ON" alias="ON" value="0x0"/>
            </setting>
            <setting alias="BOREN" default="ON" name="BOREN" description="Brown-out Reset Enable">
                <option description="Brown-out Reset enabled" name="ON" alias="ON" value="0x600"/>
                <option description="Brown-out Reset enabled while running and disabled in Sleep" name="NSLEEP" alias="NSLEEP" value="0x400"/>
                <option description="Brown-out Reset controlled by the SBOREN bit in the BORCON register" name="SBODEN" alias="SBODEN" value="0x200"/>
                <option description="Brown-out Reset disabled" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="CLKOUTEN" default="OFF" name="CLKOUTEN" description="Clock Out Enable">
                <option description="CLKOUT function is disabled. I/O or oscillator function on the CLKOUT pin" name="OFF" alias="OFF" value="0x800"/>
                <option description="CLKOUT function is enabled on the CLKOUT pin" name="ON" alias="ON" value="0x0"/>
            </setting>
        </register>
        <register alias="CONFIG2" name="CONFIG2" width="0x10">
            <setting alias="WRT" default="OFF" name="WRT" description="Flash Memory Self-Write Protection">
                <option description="Write protection off" name="OFF" alias="OFF" value="0x3"/>
                <option description="000h to 1FFh write protected, 200h to FFFh may be modified by EECON control" name="BOOT" alias="BOOT" value="0x2"/>
                <option description="000h to 7FFh write protected, 800h to FFFh may be modified by EECON control" name="HALF" alias="HALF" value="0x1"/>
                <option description="000h to FFFh write protected, no addresses may be modified by EECON control" name="ALL" alias="ALL" value="0x0"/>
            </setting>
            <setting alias="PPS1WAY" default="ON" name="PPS1WAY" description="PPSLOCK bit One-Way Set Enable bit">
                <option description="PPSLOCKED Bit Can Be Cleared &amp; Set Once" name="ON" alias="ON" value="0x4"/>
                <option description="PPSLOCKED Bit Can Be Cleared &amp; Set Repeatedly" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="PLLEN" default="ON" name="PLLEN" description="PLL Enable">
                <option description="4x PLL enabled" name="ON" alias="ON" value="0x100"/>
                <option description="4x PLL disabled" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="STVREN" default="ON" name="STVREN" description="Stack Overflow/Underflow Reset Enable">
                <option description="Stack Overflow or Underflow will cause a Reset" name="ON" alias="ON" value="0x200"/>
                <option description="Stack Overflow or Underflow will not cause a Reset" name="OFF" alias="OFF" value="0x0"/>
            </setting>
            <setting alias="BORV" default="LO" name="BORV" description="Brown-out Reset Voltage Selection">
                <option description="Brown-out Reset Voltage (Vbor), low trip point selected." name="LO" alias="LO" value="0x400"/>
                <option description="Brown-out Reset Voltage (Vbor), high trip point selected." name="HI" alias="HI" value="0x0"/>
            </setting>
            <setting alias="LPBOREN" default="OFF" name="LPBOREN" description="Low Power Brown-out Reset enable bit">
                <option description="LPBOR is disabled" name="OFF" alias="OFF" value="0x800"/>
                <option description="LPBOR is enabled" name="ON" alias="ON" value="0x0"/>
            </setting>
            <setting alias="LVP" default="ON" name="LVP" description="Low-Voltage Programming Enable">
                <option description="Low-voltage programming enabled" name="ON" alias="ON" value="0x2000"/>
                <option description="High-voltage on MCLR/VPP must be used for programming" name="OFF" alias="OFF" value="0x0"/>
            </setting>
        </register>
        <modules>
            <module group="Internal Oscillator" name="INTERNAL OSCILLATOR" type="osc" version="v0" sub_version="a0" instance="">
                <property name="PLLType" value="4XPLL"/>
                <property name="freqMaxEC" value="32000000"/>
                <property name="freqMaxHS" value="16000000"/>
                <property name="freqMinPLLEC" value="4000000"/>
                <property name="freqMinPLLINTOSC" value="4000000"/>
                <property name="freqMaxPLLEC" value="8000000"/>
                <property name="freqMaxPLLINTOSC" value="8000000"/>
                <property name="LFINTOSC" value="31000"/>
                <property name="HFINTOSC" value="16000000"/>
                <property name="MFINTOSC" value="500000"/>
                <register alias="OSCCON" name="OSCCON" type="R,W" width="8">
                    <setting alias="SPLLEN" default="disabled" name="SPLLEN" mask="0x80" type="R,W" porDefault="0x0">
                        <option name="disabled" alias="disabled" value="0x0"/>
                        <option name="enabled" alias="enabled" value="0x1"/>
                    </setting>
                    <setting alias="IRCF" default="500KHz_MF" name="IRCF" mask="0x78" type="R,W" porDefault="0x7">
                        <option name="16MHz_HF" alias="16MHz_HF" value="0xf"/>
                        <option name="8MHz_HF" alias="8MHz_HF" value="0xe"/>
                        <option name="4MHz_HF" alias="4MHz_HF" value="0xd"/>
                        <option name="2MHz_HF" alias="2MHz_HF" value="0xc"/>
                        <option name="1MHz_HF" alias="1MHz_HF" value="0xb"/>
                        <option name="500KHz_HF" alias="500KHz_HF" value="0xa"/>
                        <option name="250KHz_HF" alias="250KHz_HF" value="0x9"/>
                        <option name="125KHz_HF" alias="125KHz_HF" value="0x8"/>
                        <option name="500KHz_MF" alias="500KHz_MF" value="0x7"/>
                        <option name="250KHz_MF" alias="250KHz_MF" value="0x6"/>
                        <option name="125KHz_MF" alias="125KHz_MF" value="0x5"/>
                        <option name="62.5KHz_MF" alias="62.5KHz_MF" value="0x4"/>
                        <option name="31.25KHz_HF" alias="31.25KHz_HF" value="0x3"/>
                        <option name="31.25KHz_MF" alias="31.25KHz_MF" value="0x2"/>
                        <option name="31KHz_LF" alias="31KHz_LF" value="0x0"/>
                    </setting>
                    <setting alias="SCS" default="FOSC" name="SCS" mask="0x3" type="R,W" porDefault="0x0">
                        <option name="INTOSC" alias="INTOSC" value="0x2"/>
                        <option name="FOSC" alias="FOSC" value="0x0"/>
                    </setting>
                </register>
                <register alias="OSCSTAT" name="OSCSTAT" type="R" width="8">
                    <setting alias="PLLR" default="disabled" name="PLLR" mask="0x40" type="R" porDefault="0x0">
                        <option name="disabled" alias="disabled" value="0x0"/>
                        <option name="enabled" alias="enabled" value="0x1"/>
                    </setting>
                    <setting alias="OSTS" default="intosc" name="OSTS" mask="0x20" type="R" porDefault="0x0">
                        <option name="intosc" alias="intosc" value="0x0"/>
                        <option name="clock" alias="clock" value="0x1"/>
